# Generated by Django 4.1.7 on 2023-08-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(default='qsqtfv', max_length=6),
        ),
    ]
